name: Docker Build Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and test containers
        run: |
          # Собираем контейнеры
          docker-compose -f docker-compose.yml build

          # Запускаем контейнеры с другим портом для PostgreSQL
          sed -i 's/5432:5432/5433:5432/g' docker-compose.yml
          docker-compose -f docker-compose.yml up -d

          # Проверяем состояние контейнеров
          docker ps -a
          docker-compose -f docker-compose.yml logs app

          # Останавливаем контейнеры
          docker-compose -f docker-compose.yml down
          git checkout docker-compose.yml
